# Generated by Django 5.1.7 on 2025-12-16 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FH_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deceased_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('male', models.BooleanField()),
                ('address', models.CharField(max_length=255)),
                ('ssn', models.IntegerField()),
                ('nok', models.CharField(max_length=255)),
                ('completed', models.BooleanField()),
                ('obituary', models.TextField()),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to=settings.AUTH_USER_MODEL)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_identification', to='myapp.fh_location')),
            ],
        ),
    ]
