# Generated by Django 5.1.7 on 2025-12-18 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fh_location_deceased_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event_deceased_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_deceased_info', to='myapp.deceased_info')),
            ],
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_service_fee', models.BooleanField()),
                ('embalming', models.BooleanField()),
                ('dress_casket_coz', models.BooleanField()),
                ('visitation', models.BooleanField()),
                ('transfer', models.BooleanField()),
                ('hearse', models.BooleanField()),
                ('casket', models.BooleanField()),
                ('urn', models.BooleanField()),
                ('cemetery', models.BooleanField()),
                ('crematory', models.BooleanField()),
                ('gratuities', models.BooleanField()),
                ('finance_deceased_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_deceased_info', to='myapp.deceased_info')),
            ],
        ),
    ]
