# Generated by Django 5.1.7 on 2025-12-18 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_events_finances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased_info',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='male',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='nok',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='obituary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='ssn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deceased_info',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
