# Generated by Django 5.1.7 on 2026-01-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_deceased_info_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
