# Generated by Django 5.1.7 on 2026-02-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_events_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased_info',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
