# Generated by Django 5.1.7 on 2026-02-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_deceased_info_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finances',
            name='basic_service_fee',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='casket',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='cemetery',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='crematory',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='dress_casket_coz',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='embalming',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='gratuities',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='hearse',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='urn',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='visitation',
        ),
        migrations.AddField(
            model_name='finances',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
