# Generated by Django 5.1.7 on 2026-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_finances_basic_service_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased_info',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
